import { z } from 'zod'

// ─── R2 key pattern generated by our own code ─────────────────────────────────
// Format: originals/<uuid>.<ext>  or  thumbnails/<uuid>.jpg
const r2KeyRegex = /^(originals|thumbnails)\/[0-9a-f-]{36}\.\w{1,10}$/

// ─── Upload presign endpoint ──────────────────────────────────────────────────
export const PresignBodySchema = z.object({
  fileName: z.string().max(255).optional(),
  contentType: z.string().max(100).regex(/^image\//),
  fileSize: z.number().int().positive(),
  prefix: z.enum(['originals', 'thumbnails']).optional(),
})

// ─── POST /api/images (save upload record) ────────────────────────────────────
export const SaveImageBodySchema = z.object({
  r2_object_key: z.string().max(500).regex(r2KeyRegex),
  thumbnail_key: z.string().max(500).regex(r2KeyRegex).nullable().optional(),
  width: z.number().int().positive().max(50_000),
  height: z.number().int().positive().max(50_000),
  file_size: z.number().int().positive().max(100 * 1024 * 1024),
  mime_type: z.string().max(100).regex(/^image\//),
  taken_at: z.string().max(50).nullable().optional(),
})

// ─── POST /api/images/from-url ────────────────────────────────────────────────
export const FromUrlBodySchema = z.object({
  // http:// or https:// only, max 2048 chars
  url: z.string().url().max(2048).refine(
    (u) => /^https?:\/\//i.test(u),
    { message: 'Only http/https URLs are allowed' }
  ),
  mode: z.enum(['reference', 'import']),
})

// ─── Server action: updateImageMetadata ──────────────────────────────────────
export const UpdateMetaSchema = z.object({
  name: z.string().max(255).trim(),
  note: z.string().max(10_000).trim(),
  albumId: z.string().uuid().nullable().optional().or(z.literal('')),
  tags: z
    .array(z.string().max(100).trim())
    .max(50)
    .default([]),
  takenAt: z.string().max(50).nullable().optional(),
})

// ─── GET /api/images list params ──────────────────────────────────────────────
export const ListParamsSchema = z.object({
  page: z.coerce.number().int().min(0).max(10_000).default(0),
  limit: z.coerce.number().int().min(1).max(50).default(30),
  album_id: z.string().uuid().optional(),
  // strip commas from q to prevent PostgREST or() syntax injection
  q: z.string().max(200).transform((s) => s.replace(/,/g, '')).optional(),
  tag: z.string().max(100).optional(),
  from: z.string().max(20).optional(),
  to: z.string().max(20).optional(),
  sort: z.enum(['uploaded_desc', 'uploaded_asc', 'taken_desc', 'taken_asc', 'name_asc']).default('uploaded_desc'),
})
